sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

install:
  - haxelib install hxcpp
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib install sure
  - haxelib list

script:
  - haxelib run openfl build "Project.xml" flash
  - haxelib run openfl build "Project.xml" html5
  - haxelib run openfl build "Project.xml" linux